
# This file is automatically generated, you probably don't want to edit this

simiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            text = NULL,
            segsize = 0, ...) {

            super$initialize(
                package="simigraph",
                name="simi",
                requiresData=TRUE,
                ...)

            private$..text <- jmvcore::OptionVariable$new(
                "text",
                text)
            private$..segsize <- jmvcore::OptionInteger$new(
                "segsize",
                segsize,
                default=0)

            self$.addOption(private$..text)
            self$.addOption(private$..segsize)
        }),
    active = list(
        text = function() private$..text$value,
        segsize = function() private$..segsize$value),
    private = list(
        ..text = NA,
        ..segsize = NA)
)

simiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Similitude Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                width=600,
                height=600,
                renderFun=".plot"))}))

simiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "simigraph",
                name = "simi",
                version = c(0,1,0),
                options = options,
                results = simiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Similitude Analysis
#'
#' 
#' @param data .
#' @param text .
#' @param segsize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
simi <- function(
    data,
    text,
    segsize = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simi requires jmvcore to be installed (restart may be required)")

    if ( ! missing(text)) text <- jmvcore::resolveQuo(jmvcore::enquo(text))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(text), text, NULL))


    options <- simiOptions$new(
        text = text,
        segsize = segsize)

    analysis <- simiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

